### PR TITLE
Adds Python 3 support, Python read(), write() functions consume and produce binary data now

### PR DESCRIPTION
**Pull request by joernesdohr**
Python 3 adaptions originally from https://github.com/TMRh20/RF24/pull/164 incorporated into the RPi/pyRF24Network/pyRF24Network.cpp Python wrapper. 

network.read() returns payload as binary data. To unpack binary data in Python 2, the payload can be unpacked with unpack(format, str(payload)) or unpack_from(format, buffer(payload)).

network.write() requires bytes or bytearray as payload data.

Updates helloworld_rx.py, helloworld_tx.py examples for Python 2, adds helloworld_rx.python3.py and helloworld_rx.python3.py for Python 3 testing.

Tested between a Raspberry Pi B Rev2 and Arduino Uno.

ps: sorry for the messy commit log, I just push and pull a lot between my desktop PC and RPi...

### CODE REVIEW

**Comment by mz-fuzzy** [comment]
@joernesdohr  
thanks for posting this! As far as I was able to check, the adaptation itself looks fine.

Examples need some more work:

(1.) don't make separate examples for python2 and python3, join it to one python2/python3 example:
- import print from futures
- in python2, it's not needed to convert bytearray to string by str(), it's an implicit conversion
- format of octal literals are different in 2 and 3, so perhaps you can use something like
```python
octlit = lambda n:int(n, 8)

this_node = octlit("00")
other_node = octlit("01")
```
check [this](https://github.com/TMRh20/RF24/blob/master/examples_RPi/pingpair_dyn.py) for inspiration.

(2.) in helloworld_tx.py, you send 'packet_sent' value twice. I think it's intended to send a millisecond timestamp instead as 1st integer - millis() should be kept there and the millis function should be changed in order that the result fits to 4 bytes:
```python
millis = lambda: int(round(time.time() * 1000)) & 0xffffffff
```

(3.) remove build directory from the pull request including .o files

**Comment by joernesdohr** [comment]
Thanks for the feedback! The future module looks pretty neat, didn't know about that.

> •in python2, it's not needed to convert bytearray to string by str(), it's an implicit conversion

Looks like this was only added in Python 2.7.5 for unpack as this conversation mentions: http://stackoverflow.com/questions/20612587/struct-unpack-with-bytearrays

I only receive the following error with 2.7.3:

    struct.error: unpack requires a string argument of length 8

Wrapping payload in bytes() solves the issue though, and is compatible with both Python 2 and 3.

**Comment by joernesdohr** [comment]
I incorporated all your suggestions into my fork.

**Comment by TMRh20** [comment]
Not sure if this was fully ready to be merged, but it seems to work for me so far.

**Pull request merged**
