### PR TITLE
Intel Galileo Support for Development Library

### PR DESCRIPTION
**Pull request by spaniakos**
just added support for the Development library

### CODE REVIEW

**Comment by TMRh20** [comment]
@spaniakos  Hmm, it looks like this pushed to master, not development?

**Comment by spaniakos** [comment]
Probabaly i bad pull request . Can u revert the changes and i will make a
new one with development and restore my master branch if i meshed up.

**Comment by TMRh20** [comment]
I just took a closer look at both branches, and I see the commits for Galileo support on both of them, so I think we just had Dev/Master backwards. The changes look good to me otherwise, could you take a look before reverting?

**Comment by spaniakos** [comment]
Sure i will make tests in both , but i need 2 hours to go to my equipment.

**Comment by spaniakos** [comment]
yep , i see the mistake , initialy i pushed to master. then i reverted back and pushed to Development
but i havent changed the pull request to development branch.
therefore i need to redo the pull request.

you have just accepted a bulk pull request contained nothing but the revised changes for master.

**Pull request merged**
