### PR TITLE
  Add AES encryption, multi packet write and read, simple sleep  https://github.com/pat1/RF24Network

### PR DESCRIPTION
**Pull request by pat1**
I am trying to add some functioanlity:

a) AES encryption use  https://github.com/DavyLandman/AESLib  and is obtained adding Key and IV parameter to begin.
b) Multipackey is experimental but it seem work for now. The receive buffer is lifo and I need for a simple 
behaviou fifo; I have added a very simple fifo over lifo.
c) I have added a simple sleep to wake up when a packet was received. (it works)

### CODE REVIEW

**Comment by Avamander** [comment]
This seems really nice. What's the status of this now? Should this pull request be closed @TMRh20 @pat1 ?

**Comment by TMRh20** [comment]
@Avamander Its complicated lol.

Definitely some good ideas here, but needs more discussion and input to figure out imho.

We currently have a working implementation of fragementation/reassembly along with sleep mode in the RF24Network lib, so that mainly leaves encryption and/or signing support.

If you take a look at the [thread here](http://forum.mysensors.org/topic/1021/security-introducing-signing-support-to-mysensors) there is some very good information regarding the mysensors signing support, and why they opted not to use encryption.

I tend to think mostly along the same path, in that RF24 is generally not going to be used for transfer of highly sensitive information, with authentication and verification being more important than encryption. As well, the typical examples for things like the AES lib generally work for encrypting a single piece of information, but ensuring a secure exchange over time is more complicated from what I understand.

Any input here is helpful though.

**Comment by Avamander** [comment]
The functionality could/should be maybe added to RF24Mesh as an optional feature. Signing/encrypting packages adds a small layer of security, making RF24Mesh (NRF24L01+) a better choice for those who are building a home automation system. There are quite a few papers written on this subject (http://www.lcc.uma.es/~roman/files/roman-ccnc06.pdf for example) that might help a bit deciding.

**Comment by TMRh20** [comment]
Just to add to the conversation, I was playing around a bit with [this lib](http://www.forward.com.au/pfod/SipHashLibrary/) a while back, and it seemed to be 'working' but haven't been able to investigate much further. At the time, I ended up incorporating it largely into RF24Network, because I had a hard time making it so seamless in an RF24Mesh application. [Theoretically](https://en.wikipedia.org/wiki/OSI_model), however that doesn't seem to be the correct place for it.

**Pull request closed without merging**
