### PR TITLE
Update RF24Network_config.h

### PR DESCRIPTION
**Pull request by aaddame**
Don't enable sleep on ESP8266

### CODE REVIEW

**Comment by Avamander** [comment]
What's the issue when you do enable sleep on ESP8266? I am not familiar with the device so sorry for asking.

**Comment by aaddame** [comment]
Compilation error

"/home/aad/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/aad/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L   -DARDUINO=10608 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266  -DESP8266 "-I/home/aad/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" "-I/home/aad/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" "-I/home/aad/Arduino/libraries/RF24Mesh" "-I/home/aad/Arduino/libraries/RF24" "-I/home/aad/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/SPI" "-I/home/aad/Arduino/libraries/RF24Network" "-I/home/aad/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" "-I/home/aad/Arduino/libraries/ArduinoJson/src" "-I/home/aad/Arduino/libraries/PubSubClient/src" "-I/home/aad/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" "/home/aad/Arduino/libraries/RF24Network/RF24Network.cpp" -o "/tmp/build207476dfaadc774b71f05f4d703ec648.tmp/libraries/RF24Network/RF24Network.cpp.o"
/home/aad/Arduino/libraries/RF24Network/RF24Network.cpp:30:24: fatal error: avr/sleep.h: No such file or directory
  #include <avr/sleep.h>
                        ^
compilation terminated.

**Comment by TMRh20** [comment]
I think it might clean things up a bit to use ``` #if defined (ARDUINO_ARCH_AVR) ``` at https://github.com/TMRh20/RF24Network/blob/master/RF24Network.cpp#L1280 instead of the current defines

**Comment by aaddame** [comment]
That doesn't solve the compilation error.
Defining ENABLE_SLEEP_MODE puls in <avr/sleep.h>

#if defined (ENABLE_SLEEP_MODE) && !defined (RF24_LINUX) && !defined
(__ARDUINO_X86__)
#include <avr/sleep.h>
#include <avr/power.h>
volatile byte sleep_cycles_remaining;
volatile bool wasInterrupted;
#endif

This file cannot be found in the esp8266 include directories

2016-04-15 6:24 GMT+02:00 TMRh20 <notifications@github.com>:

**Comment by TMRh20** [comment]
Heh, thanks, I guess that line should be changed to ``` #if defined (ENABLE_SLEEP_MODE) && defined (ARDUINO_ARCH_AVR) ``` to match.

**Comment by aaddame** [comment]
Yes, changing both defines does the job

**Pull request merged**
